### ISSUE TITLE
ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by poohzaza166** [Defxult/discordLevelingSystem#13]
python version 3.8.10
pycord 2.0

Traceback (most recent call last):
  File "/mnt/sharessd/code/python/utachi-refractor/ablelevel.py", line 3, in <module>
    from discordLevelingSystem import DiscordLevelingSystem
  File "/home/pooh/.local/share/virtualenvs/utachi-refractor-hCTN_qea/lib/python3.8/site-packages/discordLevelingSystem/__init__.py", line 12, in <module>
    from .announcement import LevelUpAnnouncement
  File "/home/pooh/.local/share/virtualenvs/utachi-refractor-hCTN_qea/lib/python3.8/site-packages/discordLevelingSystem/announcement.py", line 70, in <module>
    class LevelUpAnnouncement:
  File "/home/pooh/.local/share/virtualenvs/utachi-refractor-hCTN_qea/lib/python3.8/site-packages/discordLevelingSystem/announcement.py", line 141, in LevelUpAnnouncement
    def __init__(self, message: Union[str, Embed]=default_message, level_up_channel_ids: Optional[Sequence[int]]=None, allowed_mentions: AllowedMentions=default_mentions, tts: bool=False, delete_after: Optional[float]=None):
TypeError: 'ABCMeta' object is not subscriptable

**Comment by Defxult** [comment]
Please follow the appropriate format when it comes to reporting errors/bugs

![C262F578-F840-43A0-90E6-A4E00C881FB8](https://user-images.githubusercontent.com/52070034/159497923-fe4ded82-8277-4afc-a9b8-f8eb6dc2d548.jpeg)
