### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by NotTrueFalse** [Defxult/discordLevelingSystem#23]
**Describe the bug**
When I try to install discordLevelingSystem, a error message appear, and I don't know what cause this, I laready tried to change python version, and nothing changed, tried --upgrade (still nothing), so I don't know what to do. (yes discord is installed on my computer ( I used pip install discord --upgrade), but it still say ModuleNotFoundError: No module named 'discord' ).

**To Reproduce**
```pip install discordLevelingSystem```

**Traceback if any**
```
Collecting discordLevelingSystem (from -r .\requirements.txt (line 7))
  Using cached discordLevelingSystem-1.2.0.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\ender\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ender\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\ender\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\ender\AppData\Local\Temp\pip-build-env-_ab12cde\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\ender\AppData\Local\Temp\pip-build-env-_ab12cde\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\ender\AppData\Local\Temp\pip-build-env-_ab12cde\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\ender\AppData\Local\Temp\pip-build-env-_ab12cde\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "C:\Users\ender\AppData\Local\Temp\pip-install-fghi23jk\discordlevelingsystem_8e83c0b019e441568f860ceb21d4a8fd\discordLevelingSystem\__init__.py", line 12, in <module>
          from .announcement import LevelUpAnnouncement
        File "C:\Users\ender\AppData\Local\Temp\pip-install-fghi23jk\discordlevelingsystem_8e83c0b019e441568f860ceb21d4a8fd\discordLevelingSystem\announcement.py", line 28, in <module>
          from discord import AllowedMentions, Embed, Member as DMember
      ModuleNotFoundError: No module named 'discord'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Required Checklist**
- [x] I am using discord.py 2.0 or higher
- (N/A) I am using discordLevelingSystem 1.2.0 or higher
- (N/A) I have the required [intents](https://github.com/Defxult/discordLevelingSystem#intents) enabled

**Version Info**
What's the exact version of discordLevelingSystem/discord.py are you using?
- discord.py: ```pip show discord.py
Name: discord.py
Version: 2.2.3
Summary: A Python wrapper for the Discord API
Home-page: https://github.com/Rapptz/discord.py```
- discordLevelingSystem: N/A

**Comment by Defxult** [comment]
This has been fixed as of [v1.2.1](https://pypi.org/project/discordLevelingSystem/1.2.1/). Thanks for reporting the issue! 🙂
